# name: Code Formatting
# on:
#   pull_request:
#     branches: [main]

#   # Enables a button on Actions tab
#   workflow_dispatch:

# jobs:
#   format:
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout
#         uses: actions/checkout@master
#         with:
#           ref: main

#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14.x"

#       - run: npm ci

#       - run: npm run format

#       - name: Commit changes
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git add --all
#           git commit -m "Automatic Code Formatting" || echo "No changes to commit"
#           git push
